version: '2'

services:
  mattermost:
    restart: unless-stopped
    image: telota/mattermost-team-edition
    ports:
      - "8080:80"
    environment:
      # adjust these to your needs
      - DB_PASS=password
      - MM_SERVICESETTINGS_SITEURL=http://localhost:8080
      # the following must be 32 characters long
      - MM_SQLSETTINGS_ATRESTENCRYPTKEY=long-and-random-alphanumeric-string
      - MM_FILESETTINGS_PUBLICLINKSALT=long-and-random-alphanumeric-string
      - MM_EMAILSETTINGS_PASSWORDRESETSALT=long-and-random-alphanumeric-string
      - MM_EMAILSETTINGS_INVITESALT=long-and-random-alphanumeric-string

  postgres:
    restart: unless-stopped
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=password
